#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: skj
 * Date: 2018/12/6
 * Time: 下午3:32
 */

require_once "vendor/autoload.php";

define('ROOT_PATH', __DIR__);
//配置文件路径
define('CONF_DIR', __DIR__);
//配置文件类型
define('CONF_TYPE', 'YAML'); // 'YAML' 'PHP'
//配置文件名
define('ENV', 'dev');

(new \Zero\Console\Helper())->exec($argv);
